import { DefaultSort, Quarterback, Type } from '../models/quarterback';

export const QUARTERBACKS: Quarterback[] = [
  {
    "totalRows": 13,
    "status": "OK",
    "startRow": 1,
    "queryTime": 5,
    "header": [
      {
        "desc": "Player ID",
        "name": "playerId",
        "defaultSort": DefaultSort.Asc,
        "label": "playerId",
        "formatDef": { "type": Type.Integer },
        "selectClause": "playerId"
      },
      {
        "desc": "Full Name",
        "name": "fullName",
        "defaultSort":  DefaultSort.Asc,
        "label": "fullName",
        "selectClause": "fullName"
      },
      {
        "defaultSort":  DefaultSort.Asc,
        "label": "playerImage",
        "canBeAveraged": true,
        "selectClause": "\"https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/\" + eliasPlayerId + \".png\""
      },
      {
        "desc": "Season Year",
        "name": "seasonYear",
        "defaultSort":  DefaultSort.Asc,
        "label": "seasonYear",
        "formatDef": { "type": Type.Integer },
        "selectClause": "season.seasonYear"
      },
      {
        "name": "week",
        "defaultSort":  DefaultSort.Asc,
        "label": "week",
        "formatDef": { "type": Type.Integer },
        "selectClause": "game.week"
      },
      {
        "desc": "Game Date",
        "name": "gameDate",
        "defaultSort":  DefaultSort.Asc,
        "label": "gameDate",
        "selectClause": "game.gameDate"
      },
      {
        "desc": "Abbreviated Name",
        "name": "abbrevName",
        "defaultSort":  DefaultSort.Asc,
        "label": "team",
        "selectClause": "team.game.abbrevName"
      },
      {
        "defaultSort":  DefaultSort.Asc,
        "label": "teamImage",
        "canBeAveraged": true,
        "selectClause": "\"https://static.trumedianetworks.com/images/nfl/teams/\" + team.game.teamId + \".png\""
      },
      {
        "desc": "Abbreviated Name",
        "name": "Opponent abbrevName",
        "defaultSort":  DefaultSort.Asc,
        "label": "opponent",
        "selectClause": "opponent.game.abbrevName"
      },
      {
        "defaultSort":  DefaultSort.Asc,
        "label": "opponentImage",
        "canBeAveraged": true,
        "selectClause": "\"https://static.trumedianetworks.com/images/nfl/teams/\" + opponent.game.teamId + \".png\""
      },
      {
        "name": "Pass Attempts",
        "defaultSort":  DefaultSort.Desc,
        "eventQuery": "((event.attempt AND (event.attempt != 0.0)) AND event.play)",
        "authorization": ["core"],
        "label": "Att",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[Att]"
      },
      {
        "name": "Pass Completions",
        "defaultSort":  DefaultSort.Desc,
        "eventQuery": "(event.completion AND event.play)",
        "authorization": ["core"],
        "label": "Cmp",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[Cmp]"
      },
      {
        "name": "QB Sacks",
        "defaultSort":  DefaultSort.Asc,
        "eventQuery": "event.sacked",
        "authorization": ["core"],
        "label": "Sack",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[Sack]"
      },
      {
        "name": "Pass Interceptions",
        "defaultSort":  DefaultSort.Asc,
        "eventQuery": "event.interception",
        "authorization": ["core"],
        "label": "Int",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[Int]"
      },
      {
        "name": "Passing Yards",
        "defaultSort":  DefaultSort.Desc,
        "eventQuery": "(event.passYards AND (event.passYards != 0.0))",
        "authorization": ["core"],
        "label": "PsYds",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[PsYds]"
      },
      {
        "name": "Pass Touchdowns",
        "defaultSort":  DefaultSort.Desc,
        "eventQuery": "event.passTD",
        "authorization": ["core"],
        "label": "PsTD",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[PsTD]"
      },
      {
        "name": "Rushes",
        "defaultSort":  DefaultSort.Desc,
        "eventQuery": "event.rush",
        "authorization": ["core"],
        "label": "Rush",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[Rush]"
      },
      {
        "name": "Rushing Yards",
        "defaultSort":  DefaultSort.Desc,
        "eventQuery": "(event.rushYards AND (event.rushYards != 0.0))",
        "authorization": ["core"],
        "label": "RshYds",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[RshYds]"
      },
      {
        "name": "Rushing Touchdowns",
        "defaultSort":  DefaultSort.Desc,
        "eventQuery": "event.rushTD",
        "authorization": ["core"],
        "label": "RshTD",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[RshTD]"
      }
    ],
    "rows": [
      [
        2543477,
        "Blake Bortles",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/BOR650964.png",
        2018,
        1,
        "2018-09-09 13:00:00",
        "JAX",
        "https://static.trumedianetworks.com/images/nfl/teams/2250.png",
        "NYG",
        "https://static.trumedianetworks.com/images/nfl/teams/3410.png",
        33,
        18,
        1,
        1,
        176,
        1,
        4,
        42,
        0
      ],
      [
        2543477,
        "Blake Bortles",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/BOR650964.png",
        2018,
        2,
        "2018-09-16 16:25:00",
        "JAX",
        "https://static.trumedianetworks.com/images/nfl/teams/2250.png",
        "NE",
        "https://static.trumedianetworks.com/images/nfl/teams/3200.png",
        45,
        29,
        0,
        1,
        376,
        4,
        6,
        35,
        0
      ],
      [
        2543477,
        "Blake Bortles",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/BOR650964.png",
        2018,
        3,
        "2018-09-23 13:00:00",
        "JAX",
        "https://static.trumedianetworks.com/images/nfl/teams/2250.png",
        "TEN",
        "https://static.trumedianetworks.com/images/nfl/teams/2100.png",
        34,
        21,
        3,
        0,
        155,
        0,
        5,
        27,
        0
      ],
      [
        2543477,
        "Blake Bortles",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/BOR650964.png",
        2018,
        4,
        "2018-09-30 13:00:00",
        "JAX",
        "https://static.trumedianetworks.com/images/nfl/teams/2250.png",
        "NYJ",
        "https://static.trumedianetworks.com/images/nfl/teams/3430.png",
        38,
        29,
        2,
        1,
        388,
        2,
        3,
        28,
        0
      ],
      [
        2543477,
        "Blake Bortles",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/BOR650964.png",
        2018,
        5,
        "2018-10-07 13:00:00",
        "JAX",
        "https://static.trumedianetworks.com/images/nfl/teams/2250.png",
        "KC",
        "https://static.trumedianetworks.com/images/nfl/teams/2310.png",
        61,
        33,
        5,
        4,
        430,
        1,
        4,
        34,
        1
      ],
      [
        2543477,
        "Blake Bortles",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/BOR650964.png",
        2018,
        6,
        "2018-10-14 16:25:00",
        "JAX",
        "https://static.trumedianetworks.com/images/nfl/teams/2250.png",
        "DAL",
        "https://static.trumedianetworks.com/images/nfl/teams/1200.png",
        26,
        15,
        3,
        1,
        149,
        1,
        4,
        22,
        0
      ],
      [
        2543477,
        "Blake Bortles",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/BOR650964.png",
        2018,
        7,
        "2018-10-21 13:00:00",
        "JAX",
        "https://static.trumedianetworks.com/images/nfl/teams/2250.png",
        "HOU",
        "https://static.trumedianetworks.com/images/nfl/teams/2120.png",
        12,
        6,
        0,
        0,
        61,
        0,
        6,
        30,
        0
      ],
      [
        2543477,
        "Blake Bortles",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/BOR650964.png",
        2018,
        8,
        "2018-10-28 09:30:00",
        "JAX",
        "https://static.trumedianetworks.com/images/nfl/teams/2250.png",
        "PHI",
        "https://static.trumedianetworks.com/images/nfl/teams/3700.png",
        41,
        24,
        4,
        0,
        286,
        1,
        8,
        43,
        0
      ],
      [
        2543477,
        "Blake Bortles",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/BOR650964.png",
        2018,
        10,
        "2018-11-11 13:00:00",
        "JAX",
        "https://static.trumedianetworks.com/images/nfl/teams/2250.png",
        "IND",
        "https://static.trumedianetworks.com/images/nfl/teams/2200.png",
        38,
        26,
        0,
        0,
        320,
        2,
        2,
        8,
        0
      ],
      [
        2543477,
        "Blake Bortles",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/BOR650964.png",
        2018,
        11,
        "2018-11-18 13:00:00",
        "JAX",
        "https://static.trumedianetworks.com/images/nfl/teams/2250.png",
        "PIT",
        "https://static.trumedianetworks.com/images/nfl/teams/3900.png",
        18,
        10,
        6,
        0,
        104,
        0,
        2,
        17,
        0
      ],
      [
        2543477,
        "Blake Bortles",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/BOR650964.png",
        2018,
        12,
        "2018-11-25 13:00:00",
        "JAX",
        "https://static.trumedianetworks.com/images/nfl/teams/2250.png",
        "BUF",
        "https://static.trumedianetworks.com/images/nfl/teams/610.png",
        23,
        12,
        3,
        2,
        127,
        1,
        6,
        39,
        0
      ],
      [
        2543477,
        "Blake Bortles",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/BOR650964.png",
        2018,
        16,
        "2018-12-23 13:00:00",
        "JAX",
        "https://static.trumedianetworks.com/images/nfl/teams/2250.png",
        "MIA",
        "https://static.trumedianetworks.com/images/nfl/teams/2700.png",
        6,
        5,
        1,
        0,
        39,
        0,
        4,
        25,
        0
      ],
      [
        2543477,
        "Blake Bortles",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/BOR650964.png",
        2018,
        17,
        "2018-12-30 13:00:00",
        "JAX",
        "https://static.trumedianetworks.com/images/nfl/teams/2250.png",
        "HOU",
        "https://static.trumedianetworks.com/images/nfl/teams/2120.png",
        28,
        15,
        3,
        1,
        107,
        0,
        4,
        15,
        0
      ]
    ]
  },
  {
    "totalRows": 16,
    "status": "OK",
    "startRow": 1,
    "queryTime": 6,
    "header": [
      {
        "desc": "Player ID",
        "name": "playerId",
        "defaultSort": DefaultSort.Asc,
        "label": "playerId",
        "formatDef": { "type": Type.Integer },
        "selectClause": "playerId"
      },
      {
        "desc": "Full Name",
        "name": "fullName",
        "defaultSort": DefaultSort.Asc,
        "label": "fullName",
        "selectClause": "fullName"
      },
      {
        "defaultSort": DefaultSort.Asc,
        "label": "playerImage",
        "canBeAveraged": true,
        "selectClause": "\"https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/\" + eliasPlayerId + \".png\""
      },
      {
        "desc": "Season Year",
        "name": "seasonYear",
        "defaultSort": DefaultSort.Asc,
        "label": "seasonYear",
        "formatDef": { "type": Type.Integer },
        "selectClause": "season.seasonYear"
      },
      {
        "name": "week",
        "defaultSort": DefaultSort.Asc,
        "label": "week",
        "formatDef": { "type": Type.Integer },
        "selectClause": "game.week"
      },
      {
        "desc": "Game Date",
        "name": "gameDate",
        "defaultSort": DefaultSort.Asc,
        "label": "gameDate",
        "selectClause": "game.gameDate"
      },
      {
        "desc": "Abbreviated Name",
        "name": "abbrevName",
        "defaultSort": DefaultSort.Asc,
        "label": "team",
        "selectClause": "team.game.abbrevName"
      },
      {
        "defaultSort": DefaultSort.Asc,
        "label": "teamImage",
        "canBeAveraged": true,
        "selectClause": "\"https://static.trumedianetworks.com/images/nfl/teams/\" + team.game.teamId + \".png\""
      },
      {
        "desc": "Abbreviated Name",
        "name": "Opponent abbrevName",
        "defaultSort": DefaultSort.Asc,
        "label": "opponent",
        "selectClause": "opponent.game.abbrevName"
      },
      {
        "defaultSort": DefaultSort.Asc,
        "label": "opponentImage",
        "canBeAveraged": true,
        "selectClause": "\"https://static.trumedianetworks.com/images/nfl/teams/\" + opponent.game.teamId + \".png\""
      },
      {
        "name": "Pass Attempts",
        "defaultSort": DefaultSort.Desc,
        "eventQuery": "((event.attempt AND (event.attempt != 0.0)) AND event.play)",
        "authorization": ["core"],
        "label": "Att",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[Att]"
      },
      {
        "name": "Pass Completions",
        "defaultSort": DefaultSort.Desc,
        "eventQuery": "(event.completion AND event.play)",
        "authorization": ["core"],
        "label": "Cmp",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[Cmp]"
      },
      {
        "name": "QB Sacks",
        "defaultSort": DefaultSort.Asc,
        "eventQuery": "event.sacked",
        "authorization": ["core"],
        "label": "Sack",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[Sack]"
      },
      {
        "name": "Pass Interceptions",
        "defaultSort": DefaultSort.Asc,
        "eventQuery": "event.interception",
        "authorization": ["core"],
        "label": "Int",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[Int]"
      },
      {
        "name": "Passing Yards",
        "defaultSort": DefaultSort.Desc,
        "eventQuery": "(event.passYards AND (event.passYards != 0.0))",
        "authorization": ["core"],
        "label": "PsYds",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[PsYds]"
      },
      {
        "name": "Pass Touchdowns",
        "defaultSort": DefaultSort.Desc,
        "eventQuery": "event.passTD",
        "authorization": ["core"],
        "label": "PsTD",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[PsTD]"
      },
      {
        "name": "Rushes",
        "defaultSort": DefaultSort.Desc,
        "eventQuery": "event.rush",
        "authorization": ["core"],
        "label": "Rush",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[Rush]"
      },
      {
        "name": "Rushing Yards",
        "defaultSort": DefaultSort.Desc,
        "eventQuery": "(event.rushYards AND (event.rushYards != 0.0))",
        "authorization": ["core"],
        "label": "RshYds",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[RshYds]"
      },
      {
        "name": "Rushing Touchdowns",
        "defaultSort": DefaultSort.Desc,
        "eventQuery": "event.rushTD",
        "authorization": ["core"],
        "label": "RshTD",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[RshTD]"
      }
    ],
    "rows": [
      [
        2543499,
        "Derek Carr",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/CAR358797.png",
        2018,
        1,
        "2018-09-10 22:20:00",
        "OAK",
        "https://static.trumedianetworks.com/images/nfl/teams/2520.png",
        "LA",
        "https://static.trumedianetworks.com/images/nfl/teams/2510.png",
        40,
        29,
        1,
        3,
        303,
        0,
        2,
        1,
        0
      ],
      [
        2543499,
        "Derek Carr",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/CAR358797.png",
        2018,
        2,
        "2018-09-16 16:25:00",
        "OAK",
        "https://static.trumedianetworks.com/images/nfl/teams/2520.png",
        "DEN",
        "https://static.trumedianetworks.com/images/nfl/teams/1400.png",
        32,
        29,
        1,
        0,
        288,
        1,
        0,
        0,
        0
      ],
      [
        2543499,
        "Derek Carr",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/CAR358797.png",
        2018,
        3,
        "2018-09-23 13:00:00",
        "OAK",
        "https://static.trumedianetworks.com/images/nfl/teams/2520.png",
        "MIA",
        "https://static.trumedianetworks.com/images/nfl/teams/2700.png",
        39,
        27,
        3,
        2,
        345,
        1,
        2,
        -2,
        0
      ],
      [
        2543499,
        "Derek Carr",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/CAR358797.png",
        2018,
        4,
        "2018-09-30 16:05:00",
        "OAK",
        "https://static.trumedianetworks.com/images/nfl/teams/2520.png",
        "CLE",
        "https://static.trumedianetworks.com/images/nfl/teams/1050.png",
        58,
        35,
        3,
        2,
        437,
        4,
        2,
        1,
        0
      ],
      [
        2543499,
        "Derek Carr",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/CAR358797.png",
        2018,
        5,
        "2018-10-07 16:05:00",
        "OAK",
        "https://static.trumedianetworks.com/images/nfl/teams/2520.png",
        "LAC",
        "https://static.trumedianetworks.com/images/nfl/teams/4400.png",
        33,
        24,
        3,
        1,
        268,
        1,
        1,
        5,
        0
      ],
      [
        2543499,
        "Derek Carr",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/CAR358797.png",
        2018,
        6,
        "2018-10-14 13:00:00",
        "OAK",
        "https://static.trumedianetworks.com/images/nfl/teams/2520.png",
        "SEA",
        "https://static.trumedianetworks.com/images/nfl/teams/4600.png",
        31,
        23,
        6,
        0,
        142,
        0,
        4,
        31,
        0
      ],
      [
        2543499,
        "Derek Carr",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/CAR358797.png",
        2018,
        8,
        "2018-10-28 16:05:00",
        "OAK",
        "https://static.trumedianetworks.com/images/nfl/teams/2520.png",
        "IND",
        "https://static.trumedianetworks.com/images/nfl/teams/2200.png",
        28,
        21,
        0,
        0,
        244,
        3,
        2,
        0,
        1
      ],
      [
        2543499,
        "Derek Carr",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/CAR358797.png",
        2018,
        9,
        "2018-11-01 20:20:00",
        "OAK",
        "https://static.trumedianetworks.com/images/nfl/teams/2520.png",
        "SF",
        "https://static.trumedianetworks.com/images/nfl/teams/4500.png",
        21,
        16,
        7,
        0,
        171,
        0,
        3,
        5,
        0
      ],
      [
        2543499,
        "Derek Carr",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/CAR358797.png",
        2018,
        10,
        "2018-11-11 16:05:00",
        "OAK",
        "https://static.trumedianetworks.com/images/nfl/teams/2520.png",
        "LAC",
        "https://static.trumedianetworks.com/images/nfl/teams/4400.png",
        37,
        24,
        4,
        0,
        243,
        0,
        2,
        2,
        0
      ],
      [
        2543499,
        "Derek Carr",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/CAR358797.png",
        2018,
        11,
        "2018-11-18 16:05:00",
        "OAK",
        "https://static.trumedianetworks.com/images/nfl/teams/2520.png",
        "ARI",
        "https://static.trumedianetworks.com/images/nfl/teams/3800.png",
        31,
        19,
        4,
        0,
        192,
        2,
        0,
        0,
        0
      ],
      [
        2543499,
        "Derek Carr",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/CAR358797.png",
        2018,
        12,
        "2018-11-25 13:00:00",
        "OAK",
        "https://static.trumedianetworks.com/images/nfl/teams/2520.png",
        "BAL",
        "https://static.trumedianetworks.com/images/nfl/teams/325.png",
        34,
        16,
        3,
        0,
        194,
        1,
        0,
        0,
        0
      ],
      [
        2543499,
        "Derek Carr",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/CAR358797.png",
        2018,
        13,
        "2018-12-02 16:05:00",
        "OAK",
        "https://static.trumedianetworks.com/images/nfl/teams/2520.png",
        "KC",
        "https://static.trumedianetworks.com/images/nfl/teams/2310.png",
        38,
        29,
        3,
        0,
        285,
        3,
        1,
        8,
        0
      ],
      [
        2543499,
        "Derek Carr",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/CAR358797.png",
        2018,
        14,
        "2018-12-09 16:25:00",
        "OAK",
        "https://static.trumedianetworks.com/images/nfl/teams/2520.png",
        "PIT",
        "https://static.trumedianetworks.com/images/nfl/teams/3900.png",
        34,
        25,
        4,
        0,
        322,
        2,
        1,
        -1,
        0
      ],
      [
        2543499,
        "Derek Carr",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/CAR358797.png",
        2018,
        15,
        "2018-12-16 13:00:00",
        "OAK",
        "https://static.trumedianetworks.com/images/nfl/teams/2520.png",
        "CIN",
        "https://static.trumedianetworks.com/images/nfl/teams/920.png",
        38,
        21,
        5,
        0,
        263,
        1,
        0,
        0,
        0
      ],
      [
        2543499,
        "Derek Carr",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/CAR358797.png",
        2018,
        16,
        "2018-12-24 20:15:00",
        "OAK",
        "https://static.trumedianetworks.com/images/nfl/teams/2520.png",
        "DEN",
        "https://static.trumedianetworks.com/images/nfl/teams/1400.png",
        26,
        19,
        1,
        0,
        167,
        0,
        4,
        -3,
        0
      ],
      [
        2543499,
        "Derek Carr",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/CAR358797.png",
        2018,
        17,
        "2018-12-30 16:25:00",
        "OAK",
        "https://static.trumedianetworks.com/images/nfl/teams/2520.png",
        "KC",
        "https://static.trumedianetworks.com/images/nfl/teams/2310.png",
        33,
        24,
        3,
        2,
        185,
        0,
        0,
        0,
        0
      ]
    ]
  },
  {
    "totalRows": 14,
    "status": "OK",
    "startRow": 1,
    "queryTime": 5,
    "header": [
      {
        "desc": "Player ID",
        "name": "playerId",
        "defaultSort": DefaultSort.Asc,
        "label": "playerId",
        "formatDef": { "type": Type.Integer },
        "selectClause": "playerId"
      },
      {
        "desc": "Full Name",
        "name": "fullName",
        "defaultSort": DefaultSort.Asc,
        "label": "fullName",
        "selectClause": "fullName"
      },
      {
        "defaultSort": DefaultSort.Asc,
        "label": "playerImage",
        "canBeAveraged": true,
        "selectClause": "\"https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/\" + eliasPlayerId + \".png\""
      },
      {
        "desc": "Season Year",
        "name": "seasonYear",
        "defaultSort": DefaultSort.Asc,
        "label": "seasonYear",
        "formatDef": { "type": Type.Integer },
        "selectClause": "season.seasonYear"
      },
      {
        "name": "week",
        "defaultSort": DefaultSort.Asc,
        "label": "week",
        "formatDef": { "type": Type.Integer },
        "selectClause": "game.week"
      },
      {
        "desc": "Game Date",
        "name": "gameDate",
        "defaultSort": DefaultSort.Asc,
        "label": "gameDate",
        "selectClause": "game.gameDate"
      },
      {
        "desc": "Abbreviated Name",
        "name": "abbrevName",
        "defaultSort": DefaultSort.Asc,
        "label": "team",
        "selectClause": "team.game.abbrevName"
      },
      {
        "defaultSort": DefaultSort.Asc,
        "label": "teamImage",
        "canBeAveraged": true,
        "selectClause": "\"https://static.trumedianetworks.com/images/nfl/teams/\" + team.game.teamId + \".png\""
      },
      {
        "desc": "Abbreviated Name",
        "name": "Opponent abbrevName",
        "defaultSort": DefaultSort.Asc,
        "label": "opponent",
        "selectClause": "opponent.game.abbrevName"
      },
      {
        "defaultSort": DefaultSort.Asc,
        "label": "opponentImage",
        "canBeAveraged": true,
        "selectClause": "\"https://static.trumedianetworks.com/images/nfl/teams/\" + opponent.game.teamId + \".png\""
      },
      {
        "name": "Pass Attempts",
        "defaultSort": DefaultSort.Desc,
        "eventQuery": "((event.attempt AND (event.attempt != 0.0)) AND event.play)",
        "authorization": ["core"],
        "label": "Att",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[Att]"
      },
      {
        "name": "Pass Completions",
        "defaultSort": DefaultSort.Desc,
        "eventQuery": "(event.completion AND event.play)",
        "authorization": ["core"],
        "label": "Cmp",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[Cmp]"
      },
      {
        "name": "QB Sacks",
        "defaultSort": DefaultSort.Asc,
        "eventQuery": "event.sacked",
        "authorization": ["core"],
        "label": "Sack",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[Sack]"
      },
      {
        "name": "Pass Interceptions",
        "defaultSort": DefaultSort.Asc,
        "eventQuery": "event.interception",
        "authorization": ["core"],
        "label": "Int",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[Int]"
      },
      {
        "name": "Passing Yards",
        "defaultSort": DefaultSort.Desc,
        "eventQuery": "(event.passYards AND (event.passYards != 0.0))",
        "authorization": ["core"],
        "label": "PsYds",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[PsYds]"
      },
      {
        "name": "Pass Touchdowns",
        "defaultSort": DefaultSort.Desc,
        "eventQuery": "event.passTD",
        "authorization": ["core"],
        "label": "PsTD",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[PsTD]"
      },
      {
        "name": "Rushes",
        "defaultSort": DefaultSort.Desc,
        "eventQuery": "event.rush",
        "authorization": ["core"],
        "label": "Rush",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[Rush]"
      },
      {
        "name": "Rushing Yards",
        "defaultSort": DefaultSort.Desc,
        "eventQuery": "(event.rushYards AND (event.rushYards != 0.0))",
        "authorization": ["core"],
        "label": "RshYds",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[RshYds]"
      },
      {
        "name": "Rushing Touchdowns",
        "defaultSort": DefaultSort.Desc,
        "eventQuery": "event.rushTD",
        "authorization": ["core"],
        "label": "RshTD",
        "canBeAveraged": true,
        "formatDef": { "type": Type.Integer },
        "selectClause": "[RshTD]"
      }
    ],
    "rows": [
      [
        2560800,
        "Baker Mayfield",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/MAY483453.png",
        2018,
        3,
        "2018-09-20 20:20:00",
        "CLE",
        "https://static.trumedianetworks.com/images/nfl/teams/1050.png",
        "NYJ",
        "https://static.trumedianetworks.com/images/nfl/teams/3430.png",
        23,
        17,
        1,
        0,
        201,
        0,
        2,
        -2,
        0
      ],
      [
        2560800,
        "Baker Mayfield",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/MAY483453.png",
        2018,
        4,
        "2018-09-30 16:05:00",
        "CLE",
        "https://static.trumedianetworks.com/images/nfl/teams/1050.png",
        "OAK",
        "https://static.trumedianetworks.com/images/nfl/teams/2520.png",
        41,
        21,
        2,
        2,
        295,
        2,
        4,
        10,
        0
      ],
      [
        2560800,
        "Baker Mayfield",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/MAY483453.png",
        2018,
        5,
        "2018-10-07 13:00:00",
        "CLE",
        "https://static.trumedianetworks.com/images/nfl/teams/1050.png",
        "BAL",
        "https://static.trumedianetworks.com/images/nfl/teams/325.png",
        43,
        25,
        5,
        1,
        342,
        1,
        2,
        23,
        0
      ],
      [
        2560800,
        "Baker Mayfield",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/MAY483453.png",
        2018,
        6,
        "2018-10-14 13:00:00",
        "CLE",
        "https://static.trumedianetworks.com/images/nfl/teams/1050.png",
        "LAC",
        "https://static.trumedianetworks.com/images/nfl/teams/4400.png",
        46,
        22,
        5,
        2,
        238,
        1,
        2,
        8,
        0
      ],
      [
        2560800,
        "Baker Mayfield",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/MAY483453.png",
        2018,
        7,
        "2018-10-21 13:00:00",
        "CLE",
        "https://static.trumedianetworks.com/images/nfl/teams/1050.png",
        "TB",
        "https://static.trumedianetworks.com/images/nfl/teams/4900.png",
        34,
        23,
        5,
        0,
        215,
        2,
        4,
        43,
        0
      ],
      [
        2560800,
        "Baker Mayfield",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/MAY483453.png",
        2018,
        8,
        "2018-10-28 13:00:00",
        "CLE",
        "https://static.trumedianetworks.com/images/nfl/teams/1050.png",
        "PIT",
        "https://static.trumedianetworks.com/images/nfl/teams/3900.png",
        36,
        22,
        2,
        1,
        180,
        2,
        1,
        9,
        0
      ],
      [
        2560800,
        "Baker Mayfield",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/MAY483453.png",
        2018,
        9,
        "2018-11-04 12:00:00",
        "CLE",
        "https://static.trumedianetworks.com/images/nfl/teams/1050.png",
        "KC",
        "https://static.trumedianetworks.com/images/nfl/teams/2310.png",
        42,
        29,
        2,
        1,
        297,
        2,
        0,
        0,
        0
      ],
      [
        2560800,
        "Baker Mayfield",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/MAY483453.png",
        2018,
        10,
        "2018-11-11 13:00:00",
        "CLE",
        "https://static.trumedianetworks.com/images/nfl/teams/1050.png",
        "ATL",
        "https://static.trumedianetworks.com/images/nfl/teams/200.png",
        20,
        17,
        0,
        0,
        216,
        3,
        6,
        20,
        0
      ],
      [
        2560800,
        "Baker Mayfield",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/MAY483453.png",
        2018,
        12,
        "2018-11-25 13:00:00",
        "CLE",
        "https://static.trumedianetworks.com/images/nfl/teams/1050.png",
        "CIN",
        "https://static.trumedianetworks.com/images/nfl/teams/920.png",
        26,
        19,
        0,
        0,
        258,
        4,
        4,
        -4,
        0
      ],
      [
        2560800,
        "Baker Mayfield",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/MAY483453.png",
        2018,
        13,
        "2018-12-02 13:00:00",
        "CLE",
        "https://static.trumedianetworks.com/images/nfl/teams/1050.png",
        "HOU",
        "https://static.trumedianetworks.com/images/nfl/teams/2120.png",
        43,
        29,
        0,
        3,
        397,
        1,
        0,
        0,
        0
      ],
      [
        2560800,
        "Baker Mayfield",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/MAY483453.png",
        2018,
        14,
        "2018-12-09 13:00:00",
        "CLE",
        "https://static.trumedianetworks.com/images/nfl/teams/1050.png",
        "CAR",
        "https://static.trumedianetworks.com/images/nfl/teams/750.png",
        22,
        18,
        1,
        0,
        238,
        1,
        4,
        2,
        0
      ],
      [
        2560800,
        "Baker Mayfield",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/MAY483453.png",
        2018,
        15,
        "2018-12-15 20:20:00",
        "CLE",
        "https://static.trumedianetworks.com/images/nfl/teams/1050.png",
        "DEN",
        "https://static.trumedianetworks.com/images/nfl/teams/1400.png",
        31,
        18,
        2,
        1,
        188,
        2,
        4,
        6,
        0
      ],
      [
        2560800,
        "Baker Mayfield",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/MAY483453.png",
        2018,
        16,
        "2018-12-23 13:00:00",
        "CLE",
        "https://static.trumedianetworks.com/images/nfl/teams/1050.png",
        "CIN",
        "https://static.trumedianetworks.com/images/nfl/teams/920.png",
        37,
        27,
        0,
        0,
        284,
        3,
        6,
        16,
        0
      ],
      [
        2560800,
        "Baker Mayfield",
        "https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/MAY483453.png",
        2018,
        17,
        "2018-12-30 16:25:00",
        "CLE",
        "https://static.trumedianetworks.com/images/nfl/teams/1050.png",
        "BAL",
        "https://static.trumedianetworks.com/images/nfl/teams/325.png",
        42,
        23,
        0,
        3,
        376,
        3,
        0,
        0,
        0
      ]
    ]
  }

];
